
platform :ios, '8.0'

use_frameworks!



flutter_application_path = '../XBFlutterModule/XBFlutterSourceModule'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'XBFlutterModule_Example' do
  
#
#  pod 'XBFlutterModule', :path => '../'
  install_all_flutter_pods(flutter_application_path)
  
end
#flutter_application_path = './flutter-module-demo'
#eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
  
#  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
